---
title: "Unit6Q3"
author: "Daniel Davieau"
date: "February 18, 2018"
output: word_document
---

```{r setup, include=FALSE, tidy=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(ggplot2)
library(pairwiseCI)
library(multcomp)
```
###ANOVA
```{r, root.dir, tidy=TRUE}
setwd("C:/Users/davxd/Documents/GitHub/myfolders/Stats Unit 6 Homework")

ex0525 <- read.table("ForRex0525.csv", sep = ",",header = TRUE)
Education <- data.frame(ex0525)
fit = aov(Income2005~Educ, data = Education)
summary(fit)
```
### 95% COnfidence Intervals
```{r, tidy=TRUE}
pairwiseCI(Income2005~Educ, data = Education)
```
### Tukey
```{r, tidy=TRUE}
gfit = glht(fit, linfct = mcp(Educ = "Tukey"))
summary(gfit,test= adjusted(type= "none"))
confint(gfit)
```
### Dunnette
```{r}
Education$Educ=relevel(Education$Educ, ref = "12")
fit = aov(Income2005~Educ, data = Education)
gfit = glht(fit, linfct = mcp(Educ = "Dunnett"))
summary(gfit)
confint(gfit)
```
  You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
